GRID_WIDTH = 30
GRID_HEIGHT = 30

GRID_CELL_SIDE_LENGTH = 10

BOARDER_WIDTH = GRID_CELL_SIDE_LENGTH * GRID_WIDTH
BOARDER_HEIGHT = GRID_CELL_SIDE_LENGTH * GRID_HEIGHT

WINDOW_WIDTH = 720
WINDOW_HEIGHT = 540